### ISSUE TITLE
Incorrect Data Showing in Incorrect Areas

### ISSUE THREAD

**Issue by ShaneAviation** [chrisindfw/ifatc-issues#14]
I'm a trainer, and today I've elected to take the user Zach_Mayer as a trainee, who failed his IFATC practical and decided to apply for training. After hitting accept assignment, I checked his unique controller code on the "check your progress" part of the website to ensure it was blank. When I checked it, I happened to see that all of my supervisor feedback (session notes) for the user Zachary_Naponic, who is currently in IFATC, showed up. 

So, in short, notes that were meant to be kept private and in the dashboard are now showing for random trainees on their progress tabs.

**Zachary_Naponic's Session Tab:** (Controller)

![2021-01-28 (16)](https://user-images.githubusercontent.com/68622529/106231416-52250780-61b7-11eb-8de0-5c25953cf1af.png)

**Zach_Mayer's Session Feedback Tab:** (Trainee)

![2021-01-28 (17)](https://user-images.githubusercontent.com/68622529/106231532-88fb1d80-61b7-11eb-9d18-8645856422a5.png)

**Comment by chrisindfw** [comment]
This has been resolved.
