### ISSUE TITLE
When Click in User ID box, shows User ID as Invalid User Even Though They Are Not Invalid

### ISSUE THREAD

**Issue by grizpac** [chrisindfw/ifatc-issues#17]
When I click inside the User ID box to copy a user ID from the if-atc site to the dashboard, the user goes to 'invalid user.' It doesn't stay as 'invalid user' and the user is definitely not 'invalid' but can be confusing/misleading if someone doesn't know any different. 

Example....

Before:
![image](https://user-images.githubusercontent.com/34166974/112001026-eb580680-8af4-11eb-9309-c8d0928819db.png)

After clicking in box to copy & paste from IF-ATC to the IF Dashboard:
![image](https://user-images.githubusercontent.com/34166974/112001096-0296f400-8af5-11eb-8d78-8bd8166e8712.png)

**Comment by chrisindfw** [comment]
Fixed! Thanks! Found an old reference to the old API
