### ISSUE TITLE
Recruiting schedule not showing

### ISSUE THREAD

**Issue by Firecracker132** [chrisindfw/ifatc-issues#28]
For the last few days when loading the recruiting schedule, it comes up with a white screen. This issue has been made aware on the discord server by other trainers. I'm opening this log to record said issue and hopefully to bring it to the attention Chris. 

<img width="1325" alt="Screen Shot 2022-05-31 at 1 03 05 AM" src="https://user-images.githubusercontent.com/45321353/171124392-d68dd0ec-5e17-4d8c-9831-8894f8aa0a2c.png">

**Comment by chrisindfw** [comment]
Sorry it slipped through. What steps can I do to reproduce it?

**Comment by chrisindfw** [comment]
It looks like we are hitting a limit of the Calendar function with simply too many entries. I am researching to see what limits it has

**Comment by chrisindfw** [comment]
I updated the page to show events in the future and one day in the past.

**Comment by Firecracker132** [comment]
Sounds good. Thanks for the help, Chris! 👍
