### ISSUE TITLE
No one-time code sent in DM

### ISSUE THREAD

**Issue by chriswing** [chrisindfw/ifatc-issues#6]
Known issue, noted in case other people have the same issue and don't need ask.
<img width="1086" alt="Screenshot 2020-12-23 at 21 00 06" src="https://user-images.githubusercontent.com/33573117/103033448-c3432080-4562-11eb-8c48-455c65535a71.png">

**Comment by chrisindfw** [comment]
Alrighty I think I found the issue. There was some odd caching happening with my server only to find out it was pointing to a file that whoknowwhy is there. Hopefully it shouldnt happen any more after you refresh.
