### ISSUE TITLE
Exclude from Activity Notification error

### ISSUE THREAD

**Issue by chriswing** [chrisindfw/ifatc-issues#7]
If you click on a profile in controllers and go to the rights tab. Then from there, use the dropdown where it says Exclude from Activity Notification. Select yes and save. A Invalid query update will appear.

<img width="1440" alt="Screenshot 2020-12-28 at 10 38 13" src="https://user-images.githubusercontent.com/33573117/103205010-dd7d5580-48f8-11eb-82a7-cb124ab30e89.png">

**Comment by chrisindfw** [comment]
Fixed. Should not be editable or save button.
