### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by chriswing** [chrisindfw/ifatc-issues#8]
When trying to log in, nothing happens.

1. First go to the website
2. Click login
3. login window appears
4. Enter login details
5. press login
6. login window disappears
7. nothing happens

https://user-images.githubusercontent.com/33573117/103275240-0e768c80-49c4-11eb-8ab0-d3f340b91126.mov

**Comment by chrisindfw** [comment]
I was doing some stuff last night so chances are you have a cached version. Can you clear your cache and try again?

**Comment by chriswing** [comment]
Unfortunately it still doesn't work after clearing my cache...

**Comment by chrisindfw** [comment]
Ok let me look again. It is working for me. What browser are you using?

**Comment by chriswing** [comment]
I'm on google chrome Version 87.0.4280.88 

Edit: Just tried Safari as well. It didn't work. Version 14.0.2 (16610.3.7.1.9)

**Comment by chriswing** [comment]
Found this issue in the console 

<img width="423" alt="Screenshot 2020-12-29 at 14 23 58" src="https://user-images.githubusercontent.com/33573117/103286894-869f7b00-49e1-11eb-939d-12a6ccd0e200.png">

**Comment by chrisindfw** [comment]
No it is something else. I see it.

**Comment by chrisindfw** [comment]
Please try again

**Comment by chriswing** [comment]
Works again. Thanks!
